import { useRouter } from "next/router";
import Content from "../components/Content";
import Head from 'next/head'
import { MicrophoneIcon, SearchIcon, FilmIcon, UserCircleIcon } from '@heroicons/react/solid'
import { useRef } from "react";
import Router from 'next/router'


const page = ({ anime }) => {
    const router = useRouter();
    const searchInputRef = useRef('');


    const handleSearch = (e) => {
        e.preventDefault();
        const term = searchInputRef.current.value;
        if (!term) return;
        router.push(`/page?term=${term}`)


    }
 
    return (
        <div>

            <Head>
                <title>{router.query.term}- Anime search</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div className="bg-yellow-300 sticky top-0 h-28  py-2 px-2 ">
                    <div className="flex items-center justify-between">
                        <FilmIcon className="h-8 w-8" onClick={() => {
                        Router.push('/')
                    }}/>


                        <UserCircleIcon className="h-8 w-8" />
                    </div>
                    <h1 className=" text-lg lg:text-3xl  flex justify-center -mt-7">Find Movies, TV shows and more</h1>

                    <form className="flex flex-col items-center w-full mx-auto flex-grow  z-10 mt-5 " onSubmit={handleSearch}>
                        <div className="flex w-full  hover:shadow-lg bg-white focus-within:shadow-lg max-w-md rounded-lg lg:rounded-full border border-gray-200 lg:px-5 lg:py-3 items-center sm:max-w-xl lg:max-w-2xl">
                            <SearchIcon className="h-5 mr-3 " />
                            <input type="text" className="flex-grow focus:outline-none  p-2" placeholder="Enter to search"
                                ref={searchInputRef}
                            />
                            <MicrophoneIcon className="h-5  text-gray-500" />
                            <button type="submit" className="hidden"> </button>
                        </div>
                    </form>
                </div>

            </main>
            <div className="ml-6 my-6">
                <h1 className="text-gray-700 text-2xl">Search results for "{router.query.term}"</h1>
            </div>


            <Content topAnime={anime} />
        </div>
    )
}

export default page
export async function getServerSideProps(context) {
    const anime = await fetch(`https://api.jikan.moe/v3/search/anime?q=${context.query.term}&order_by=title&sort=asc&limit=9`).then(res => res.json())

    return {
        props: {
            anime: anime.results
        }
    }
}
